# Generated by Django 3.1.6 on 2021-03-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='static/images/img1.jpg', upload_to='static/uploads'),
        ),
    ]
